// NOVARE RES CHALICE TRACKER DATA
// Drunk count: 92 at Novare (73 named + 19 choices)
// Draft: 5/2/26 | Bottle: 4/23/26 | Last updated: 5/3/26
// To update: edit drunk flags and push to GitHub

window.DRAFT_URL = 'https://novareresbiercafe.com/wp-content/uploads/draught.pdf';
window.BOTTLE_URL = 'https://novareresbiercafe.com/wp-content/uploads/bottlelist.pdf';

window.BEERS = [
  { id: 'bunker libbytown brown', drunk: true },
  { id: 'barreled souls east brown & down', drunk: true },
  { id: 'sam smith nut brown ale', drunk: true, bottle: { brewery: 'Sam Smith', style: 'Nut Brown Ale', abvNum: 5.0, abv: '5.0%', sz: '500 ml', price: '$10', ut: 3.5 } },
  { id: 'sam smith taddy porter', drunk: true, bottle: { brewery: 'Sam Smith', style: 'English Porter', abvNum: 5.0, abv: '5.0%', sz: '14.9 oz', price: '$10', ut: 3.6 } },
  { id: 'deschutes black butte', drunk: true, bottle: { brewery: 'Deschutes', style: 'American Porter', abvNum: 5.5, abv: '5.5%', sz: '12 oz', price: '$7', ut: 3.7 } },
  { id: 'mayflower porter', drunk: false },
  { id: 'nogne o porter', drunk: false },
  { id: 'jacks abby framinghammer series', drunk: false },
  { id: 'bissell angels series', drunk: false, bottle: { brewery: 'Bissell Brothers', style: 'BA Imperial Porter', abvNum: 12.8, abv: '12.8%', sz: '500 ml', price: '$30', ut: 4.3 } },
  { id: 'sam smith oatmeal stout', drunk: true },
  { id: 'oharas irish stout', drunk: false },
  { id: 'lake st george oatmeal stout', drunk: true },
  { id: 'harviestoun old engine oil', drunk: true, bottle: { brewery: 'Harviestoun', style: 'Scottish Craft Stout', abvNum: 6.0, abv: '6.0%', sz: '12 oz', price: '$9', ut: 3.6 } },
  { id: 'maine beer mean old tom', drunk: true },
  { id: 'north coast old rasputin', drunk: true, draft: { brewery: 'North Coast', style: 'Imperial Stout (Nitro)', abvNum: 9.0, abv: '9.0%', sz: '8 oz', price: '$8.00', ut: 4.0 } },
  { id: 'dieu du ciel peche mortel', drunk: true, draft: { brewery: 'Dieu du Ciel', style: 'Imp. Coffee Stout (Nitro)', abvNum: 9.5, abv: '9.5%', sz: '8 oz', price: '$10.00', ut: 4.3 } },
  { id: 'tributary mott the lesser', drunk: false },
  { id: 'barreled souls stay puft series', drunk: true, bottle: { brewery: 'Barreled Souls', style: 'Imperial Stout', abvNum: 11.5, abv: '11.5%', sz: '500 ml', price: '$30', ut: 4.3 } },
  { id: 'marshall wharf sexy chaos', drunk: false },
  { id: 'prairie bomb series', drunk: true },
  { id: 'lrbc straight to black:out', drunk: true },
  { id: 'pohjala pime oo series', drunk: false },
  { id: 'bissell sigil series', drunk: false },
  { id: 'de struise choice', drunk: false, bottle: { brewery: 'De Struise', style: 'BA Imperial Stout', abvNum: 13.0, abv: '13.0%', sz: '330 ml', price: '$15', ut: 4.2 } },
  { id: 'sierra nevada pale', drunk: true },
  { id: 'maine beer peeper', drunk: true, bottle: { brewery: 'Maine Beer Co.', style: 'American Pale Ale', abvNum: 5.5, abv: '5.5%', sz: '500 ml', price: '$10', ut: 3.9 } },
  { id: 'dogfish head 30 min', drunk: true },
  { id: 'tributary pale', drunk: true },
  { id: 'mast landing dh tell tale', drunk: false },
  { id: 'bissell brothers lux', drunk: false },
  { id: 'trillium fort point pale', drunk: false },
  { id: 'maine beer dinner', drunk: false, draft: { brewery: 'Maine Beer Co.', style: 'Double IPA', abvNum: 8.2, abv: '8.2%', sz: '12 oz', price: '$10.00', ut: 4.5, utUrl: 'https://untappd.com/b/maine-beer-company-dinner/519536' } },
  { id: 'sierra nevada celebration', drunk: true },
  { id: 'russian river pliny the elder', drunk: true, draft: { brewery: 'Russian River', style: 'Double IPA', abvNum: 8.0, abv: '8.0%', sz: '12 oz', price: '$9.50', ut: 4.4 } },
  { id: 'boothbay thirsty botanist', drunk: false },
  { id: 'orono the way life should be', drunk: false },
  { id: 'bissell brothers swish', drunk: false },
  { id: 'mast landing pantless thunder', drunk: true },
  { id: 'battery steele flume squared', drunk: true },
  { id: 'goodfire ddh prime', drunk: true },
  { id: 'northcoast old stock', drunk: false, bottle: { brewery: 'North Coast', style: 'British Barleywine', abvNum: 12.5, abv: '12.5%', sz: '355 ml', price: '$8', ut: 3.9 } },
  { id: 'j.w.lees harvest ale', drunk: false, bottle: { brewery: 'J.W. Lees', style: 'English Barley Wine', abvNum: 11.5, abv: '11.5%', sz: '220 ml', price: '$12', ut: 3.9 } },
  { id: 'de struise clash of the titans', drunk: false, bottle: { brewery: 'De Struise', style: 'BA Barleywine', abvNum: 12.6, abv: '12.6%', sz: '330 ml', price: '$15', ut: 4.1 } },
  { id: 'sierra nevada big foot', drunk: false },
  { id: 'coniston bluebird bitter', drunk: true },
  { id: 'green king old speckled hen', drunk: true },
  { id: 'lake st george diver pale', drunk: false },
  { id: 'ridgeway esb', drunk: true },
  { id: 'tynt meadow dark english', drunk: false, bottle: { brewery: 'Tynt Meadow', style: 'Trappist English Strong', abvNum: 7.4, abv: '7.4%', sz: '330 ml', price: '$9', ut: 3.7 } },
  { id: 'tributary esb', drunk: false },
  { id: 'st peters english ale', drunk: false, bottle: { brewery: "St Peter's", style: 'Cream Stout', abvNum: 6.5, abv: '6.5%', sz: '500 ml', price: '$10', ut: 3.4 } },
  { id: 'barreled souls munro', drunk: true },
  { id: 'cushnoc rust bucket red', drunk: true },
  { id: 'ettaler edel hell', drunk: false, bottle: { brewery: 'Ettaler', style: 'Helles Lager', abvNum: 5.0, abv: '5.0%', sz: '500 ml', price: '$9', ut: 3.4 } },
  { id: 'hofbrau original', drunk: true },
  { id: 'jacks abby house lager', drunk: false },
  { id: 'von trapp boho pils', drunk: false },
  { id: 'pilsner urquell', drunk: true },
  { id: 'schilling palmovka 12', drunk: false },
  { id: 'czechvar original', drunk: true },
  { id: 'sacred profane pale lager', drunk: false },
  { id: 'einbecker brauherren pils', drunk: false },
  { id: 'ayinger bairisch pils', drunk: true },
  { id: 'flensberger pils', drunk: false, draft: { brewery: 'Flensburger', style: 'Northern German Pils', abvNum: 4.8, abv: '4.8%', sz: '.4 L', price: '$9.00', ut: 3.3 } },
  { id: 'italiano tipopils', drunk: true, draft: { brewery: 'Birrificio Italiano', style: 'Italian Pils', abvNum: 5.2, abv: '5.2%', sz: '.3 L', price: '$9.50', ut: 3.9 } },
  { id: 'human robot hallertau pils', drunk: false },
  { id: 'sacred profane amber lager', drunk: false },
  { id: 'schilling petrin 11', drunk: false },
  { id: 'st georgenbrau kellerbier', drunk: false, draft: { brewery: 'St. Georgen Brau', style: 'Franconian Lager', abvNum: 4.9, abv: '4.9%', sz: '.5 L', price: '$9.50', ut: 3.6 }, bottle: { brewery: 'St. Georgen Brau', style: 'Franconian Lager', abvNum: 4.9, abv: '4.9%', sz: '16 oz', price: '$9', ut: 3.6 } },
  { id: 'von trapp vienna', drunk: false, bottle: { brewery: 'Von Trapp', style: 'Vienna Lager', abvNum: 5.0, abv: '5.0%', sz: '12 oz', price: '$7', ut: 3.6 } },
  { id: 'oec coolship black lager', drunk: true },
  { id: 'ayinger dunkel', drunk: false },
  { id: 'schilling modernism', drunk: true },
  { id: 'sacred profane dark lager', drunk: true },
  { id: 'ettaller hellerbock', drunk: true },
  { id: 'einbecker winterbock', drunk: false },
  { id: 'ayinger celebrator', drunk: true, draft: { brewery: 'Ayinger', style: 'Doppelbock', abvNum: 6.7, abv: '6.7%', sz: '.3 L', price: '$9.00', ut: 3.9 } },
  { id: 'weihenstephan korbinian', drunk: true },
  { id: 'samichlaus vintage', drunk: false },
  { id: 'schlenkerla rauch helles', drunk: false, bottle: { brewery: 'Schlenkerla', style: 'Rauch Helles', abvNum: 4.3, abv: '4.3%', sz: '16 oz', price: '$9', ut: 3.5 } },
  { id: 'schlenkerla maerzen', drunk: false },
  { id: 'sacred profane smoked dark lager', drunk: true },
  { id: 'ayinger brau-weisse', drunk: true },
  { id: 'schneider weisse', drunk: false },
  { id: 'plank weissbier', drunk: true },
  { id: 'schlenkerla weizen', drunk: false, bottle: { brewery: 'Schlenkerla', style: 'Smoked Wheat Beer', abvNum: 5.2, abv: '5.2%', sz: '500 ml', price: '$9', ut: 3.6 } },
  { id: 'weihenstephan vitus', drunk: true },
  { id: 'schneider aventinus', drunk: true, bottle: { brewery: 'Schneider', style: 'Dunkelweizen Doppelbock', abvNum: 8.0, abv: '8.0%', sz: '500 ml', price: '$10', ut: 4.0 } },
  { id: 'lemke berliner woodruff', drunk: false, bottle: { brewery: 'Lemke', style: 'Berliner Weisse', abvNum: 4.0, abv: '4.0%', sz: '12 oz', price: '$10', ut: 3.5 } },
  { id: 'prof fritz briem 1809 berliner', drunk: false, bottle: { brewery: 'Prof Fritz Briem', style: 'Berliner Weisse', abvNum: 5.0, abv: '5.0%', sz: '500 ml', price: '$10', ut: 3.6 } },
  { id: 'banhof leipzig gose', drunk: false },
  { id: 'ritterguts gose', drunk: true },
  { id: 'fruh kolsch', drunk: true, draft: { brewery: 'Fruh', style: 'Kolsch', abvNum: 4.8, abv: '4.8%', sz: '.4 L', price: '$8.75', ut: 3.6 } },
  { id: 'gaffel kolsch', drunk: false, bottle: { brewery: 'Gaffel', style: 'German Kolsch', abvNum: 4.8, abv: '4.8%', sz: '16.9 oz', price: '$9', ut: 3.5 } },
  { id: 'reissdorf kolsch', drunk: true },
  { id: 'uerige alt', drunk: false },
  { id: 'westmalle extra', drunk: true, draft: { brewery: 'Westmalle', style: 'Abbey Single', abvNum: 4.8, abv: '4.8%', sz: '330 ml', price: '$10', ut: 3.7 } },
  { id: 'st. bernardus extra 4', drunk: true },
  { id: 'chimay doree gold', drunk: true },
  { id: 'val dieu blonde', drunk: false },
  { id: 'cuvee de trolls', drunk: false },
  { id: 'allagash curieux', drunk: true },
  { id: 'piraat', drunk: true },
  { id: 'de dolle dulle teve', drunk: true, bottle: { brewery: 'De Dolle', style: 'Belgian Triple', abvNum: 10.0, abv: '10.0%', sz: '16 oz', price: '$13', ut: 3.9 } },
  { id: 'de dolle stille nacht', drunk: false },
  { id: 'de glazen toren ondineke', drunk: false, bottle: { brewery: 'De Glazen Toren', style: 'Belgian Tripel', abvNum: 8.5, abv: '8.5%', sz: '750 ml', price: '$22', ut: 3.8 } },
  { id: 'st bernardus tripel', drunk: true, draft: { brewery: 'St Bernardus', style: 'Belgian Tripel', abvNum: 8.0, abv: '8.0%', sz: '12 oz', price: '$10.00', ut: 4.0 } },
  { id: 'unibroue la fin du monde', drunk: true, bottle: { brewery: 'Unibroue', style: 'Belgian Tripel', abvNum: 9.0, abv: '9.0%', sz: '12 oz', price: '$9', ut: 4.0 } },
  { id: 'de garre tripel', drunk: true },
  { id: 'duvel golden strong', drunk: false, bottle: { brewery: 'Duvel', style: 'Belgian Golden Strong', abvNum: 8.5, abv: '8.5%', sz: '330 ml', price: '$9', ut: 3.9 } },
  { id: 'westmalle trippel', drunk: false, bottle: { brewery: 'Westmalle', style: 'Trappist Tripel', abvNum: 9.5, abv: '9.5%', sz: '330 ml', price: '$11', ut: 4.1 } },
  { id: 'chimay cing cents white', drunk: false, bottle: { brewery: 'Chimay', style: 'Trappist Tripel', abvNum: 8.0, abv: '8.0%', sz: '330 ml', price: '$12', ut: 3.8 } },
  { id: 'chimay cent cinquante green', drunk: true },
  { id: 'st bernardus pater 6', drunk: false, bottle: { brewery: 'St Bernardus', style: 'Abbey Dubbel', abvNum: 6.7, abv: '6.7%', sz: '330 ml', price: '$9', ut: 3.7 } },
  { id: 'westmalle dubbel', drunk: true },
  { id: 'rochefort 6', drunk: false, bottle: { brewery: 'Rochefort', style: 'Trappist Dubbel', abvNum: 7.5, abv: '7.5%', sz: '330 ml', price: '$11', ut: 3.8 } },
  { id: 'allagash foliage report', drunk: false },
  { id: 'chimay premiere red', drunk: false, bottle: { brewery: 'Chimay', style: 'Trappist Dubbel', abvNum: 7.0, abv: '7.0%', sz: '330 ml', price: '$11', ut: 3.7 } },
  { id: 'achel brune', drunk: true },
  { id: 'st bernardus prior 8', drunk: false, bottle: { brewery: 'St Bernardus', style: 'Strong Dubbel', abvNum: 8.0, abv: '8.0%', sz: '330 ml', price: '$9', ut: 4.0 } },
  { id: 'chimay grand reserve blue', drunk: false, bottle: { brewery: 'Chimay', style: 'Trappist Strong Dark', abvNum: 9.0, abv: '9.0%', sz: '330 ml', price: '$12', ut: 4.0 } },
  { id: 'st bernardus abt 12', drunk: false, bottle: { brewery: 'St Bernardus', style: 'Belgian Dark Strong', abvNum: 10.5, abv: '10.5%', sz: '330 ml', price: '$10', ut: 4.3 } },
  { id: 'rochefort 8', drunk: false, bottle: { brewery: 'Rochefort', style: 'Trappist Dark Ale', abvNum: 9.2, abv: '9.2%', sz: '330 ml', price: '$11', ut: 4.2 } },
  { id: 'rochefort 10', drunk: false, bottle: { brewery: 'Rochefort', style: 'Trappist Dark Strong', abvNum: 11.0, abv: '11.0%', sz: '330 ml', price: '$12', ut: 4.4 } },
  { id: 'de struise pannepot', drunk: true },
  { id: 'ommegang three philosophers', drunk: true },
  { id: 'rodenbach dogfish crison cru', drunk: false },
  { id: 'rodenbach grand cru', drunk: false, bottle: { brewery: 'Rodenbach', style: 'Flemish Red-Brown', abvNum: 6.0, abv: '6.0%', sz: '330 ml', price: '$9', ut: 3.9 } },
  { id: 'monks sour red', drunk: false },
  { id: 'petrus 40/40/20', drunk: false },
  { id: 'de la senne ouden vat', drunk: false },
  { id: 'dupont saison', drunk: true, bottle: { brewery: 'Dupont', style: 'Saison', abvNum: 6.5, abv: '6.5%', sz: '375 ml', price: '$12', ut: 3.9 } },
  { id: 'de ranke xx bitter', drunk: false, bottle: { brewery: 'De Ranke', style: 'Hop-Forward Saison', abvNum: 6.2, abv: '6.2%', sz: '330 ml', price: '$9', ut: 3.8 } },
  { id: 'de la senne taras boulba', drunk: true },
  { id: 'kazematten saison', drunk: false },
  { id: 'de glazen toren saison', drunk: false, bottle: { brewery: 'De Glazen Toren', style: 'Saison', abvNum: 6.5, abv: '6.5%', sz: '750 ml', price: '$22', ut: 3.7 } },
  { id: 'oxbow loretta grisette', drunk: true },
  { id: 'oude orval', drunk: true, bottle: { brewery: 'Orval', style: 'Trappist Ale (Aged)', abvNum: 6.9, abv: '6.9%', sz: '330 ml', price: '$12', ut: 4.1 } },
  { id: 'dupont avec les bons voeux', drunk: true, bottle: { brewery: 'Dupont', style: 'Strong Saison', abvNum: 9.5, abv: '9.5%', sz: '375 ml', price: '$14', ut: 4.1 } },
  { id: 'thiriez ambre', drunk: false },
  { id: 'ommegang hennepin', drunk: false },
  { id: 'allagash white', drunk: true },
  { id: 'st. bernardus witbier', drunk: true },
  { id: 'hitachino nest white', drunk: true },
  { id: 'unibroue blanche de chambly', drunk: false },
  { id: 'drie fonteinen a & g', drunk: false, bottle: { brewery: 'Drie Fonteinen', style: 'Gueuze', abvNum: 6.2, abv: '6.2%', sz: '375 ml', price: '$25', ut: 4.4 } },
  { id: 'tilquin gueze', drunk: false, bottle: { brewery: 'Tilquin', style: 'Gueuze', abvNum: 7.0, abv: '7.0%', sz: '375 ml', price: '$22', ut: 4.2 } },
  { id: 'timmermans gueuze', drunk: false },
  { id: 'girardin gueuze', drunk: true },
  { id: 'drie fonteinen kriek', drunk: false, bottle: { brewery: 'Drie Fonteinen', style: 'Oude Kriek', abvNum: 6.5, abv: '6.5%', sz: '750 ml', price: '$60', ut: 4.5 } },
  { id: 'allagash coolship resurgem', drunk: false },
  { id: 'oxbow native/wild series', drunk: false, bottle: { brewery: 'Oxbow', style: 'Spontaneous Farmhouse', abvNum: 6.0, abv: '6.0%', sz: '750 ml', price: '$45', ut: 4.0 } },
  { id: 'russian river tion series', drunk: true },
  { id: 'jester king petite prince', drunk: false },
  { id: 'plan bee barn beer', drunk: false },
  { id: 'allagash coolship red', drunk: false, draft: { brewery: 'Allagash', style: 'Spontaneous Framboise', abvNum: 5.6, abv: '5.6%', sz: '8 oz', price: '$10.50', ut: 4.2, utUrl: 'https://untappd.com/b/allagash-brewing-company-coolship-red/64052' }, bottle: { brewery: 'Allagash', style: 'Spontaneous Framboise', abvNum: 5.6, abv: '5.6%', sz: '375 ml', price: '$25', ut: 4.2, utUrl: 'https://untappd.com/b/allagash-brewing-company-coolship-red/64052' } },
  { id: 'jester king atrial rubicite', drunk: false },
  { id: 'koelbus apricot', drunk: true },
  { id: 'underberg', drunk: true },
  { id: 'fernet michaud', drunk: false },
  { id: 'anything from a porron', drunk: false },
];

window.ALL_CHOICES = [
  { slot: 'Brown Ale Choice', cat: 'Brown', drunk: false, m: [] },
  { slot: 'Nitro Stout Choice', cat: 'Stout', drunk: false, m: [{ n: 'Dieu du Ciel Peche Mortel (Nitro)', b: 'Dieu du Ciel', abv: '9.5%', sz: '8 oz', p: '$10.00', note: 'Imperial coffee stout on nitro', s: 'd', ut: 4.3 }, { n: 'North Coast Old Rasputin (Nitro)', b: 'North Coast', abv: '9.0%', sz: '8 oz', p: '$8.00', note: 'Russian imperial stout on nitro', s: 'd', ut: 4.0 }] },
  { slot: 'Oyster Stout Choice', cat: 'Stout', drunk: false, m: [] },
  { slot: 'Special Event Imperial Stout', cat: 'Imperial Stout', drunk: true, m: [] },
  { slot: 'Bartender Draft - Imp. Stout', cat: 'Imperial Stout', drunk: false, m: [{ n: 'De Struise Cuvee Delphine', b: 'De Struise', abv: '13.0%', sz: '8 oz', p: '$11.00', note: 'Black Albert in Bourbon barrels', s: 'd', ut: 4.5 }, { n: 'Pohjala Must Kuld', b: 'Pohjala', abv: '7.8%', sz: '8 oz', p: '$10.00', note: 'Baltic porter w/ lactose', s: 'd', ut: 3.9 }] },
  { slot: 'Bartender Pkg - Imp. Stout', cat: 'Imperial Stout', drunk: false, m: [{ n: 'New Holland Dragons Milk', b: 'New Holland', abv: '11.0%', sz: '12 oz', p: '$9', note: 'BA Imperial Stout (bottle)', s: 'b', ut: 4.0 }] },
  { slot: 'California Common Choice', cat: 'American Retro', drunk: false, m: [] },
  { slot: 'Cream Ale Choice', cat: 'American Retro', drunk: false, m: [] },
  { slot: 'American Porter Choice', cat: 'American Retro', drunk: false, m: [] },
  { slot: 'Pre-Prohibition Lager Choice', cat: 'American Retro', drunk: false, m: [] },
  { slot: 'American Amber Ale Choice', cat: 'American Retro', drunk: false, m: [] },
  { slot: 'Special Event Pale Ale', cat: 'American Pale', drunk: false, m: [{ n: 'Orono/DFH Brew Notes', b: 'Orono/DFH', abv: '7.2%', sz: '16 oz', p: '$9.50', note: '100% Maine IPA on draft', s: 'd', ut: 3.8 }] },
  { slot: 'Bartender Draft - Pale Ale', cat: 'American Pale', drunk: false, m: [] },
  { slot: 'Bartender Pkg - Pale Ale', cat: 'American Pale', drunk: false, m: [] },
  { slot: 'Nebco Choice', cat: 'American IPA', drunk: false, m: [] },
  { slot: 'Wet Hop IPA Choice', cat: 'American IPA', drunk: false, m: [] },
  { slot: 'Special Event IPA', cat: 'American IPA', drunk: true, m: [] },
  { slot: 'Bartender Draft - IPA', cat: 'American IPA', drunk: true, m: [] },
  { slot: 'Bartender Pkg - IPA', cat: 'American IPA', drunk: false, m: [] },
  { slot: 'The Veil Choice', cat: 'Hazy IPA', drunk: false, m: [] },
  { slot: 'Modestman Choice', cat: 'Hazy IPA', drunk: true, m: [] },
  { slot: 'Other Half Choice', cat: 'Hazy IPA', drunk: true, m: [] },
  { slot: 'Special Event Hazy IPA', cat: 'Hazy IPA', drunk: false, m: [{ n: 'Trillium Congress Street', b: 'Trillium', abv: '7.2%', sz: '16 oz', p: '$9.50', note: 'Hazy IPA on draft', s: 'd', ut: 4.2 }, { n: 'Bissell Nothing Gold', b: 'Bissell Bros', abv: '8.2%', sz: '12 oz', p: '$8.50', note: 'Hazy DIPA on draft', s: 'd', ut: 4.2 }] },
  { slot: 'Bartender Draft - Hazy IPA', cat: 'Hazy IPA', drunk: true, m: [{ n: 'Trillium Congress Street', b: 'Trillium', abv: '7.2%', sz: '16 oz', p: '$9.50', note: 'Hazy IPA on draft', s: 'd', ut: 4.2 }] },
  { slot: 'Bartender Pkg - Hazy IPA', cat: 'Hazy IPA', drunk: false, m: [] },
  { slot: 'Barreled Souls Grain Wine', cat: 'Barley Wine', drunk: false, m: [{ n: 'Liquid Riot/Oxbow Timelapse', b: 'Liquid Riot', abv: '13.0%', sz: '8 oz', p: '$9.00', note: 'Cognac BA barleywine draft', s: 'd', ut: 4.1 }] },
  { slot: 'Airline Choice (Scottish Nitro)', cat: 'British Styles', drunk: true, m: [] },
  { slot: 'Scotch Ale Choice', cat: 'British Styles', drunk: false, m: [] },
  { slot: 'Special Event Bitter/Mild', cat: 'British Styles', drunk: false, m: [{ n: 'Naiad Maine Mild (Beer Engine!)', b: 'Naiad', abv: '3.5%', sz: '16 oz', p: '$9.50', note: 'English dark mild on cask', s: 'd', ut: 3.7 }] },
  { slot: 'British Cask Pour Choice', cat: 'British Styles', drunk: true, m: [] },
  { slot: 'Bartender Draft - British', cat: 'British Styles', drunk: true, m: [{ n: 'Naiad Maine Mild (Beer Engine!)', b: 'Naiad', abv: '3.5%', sz: '16 oz', p: '$9.50', note: 'Dark mild on cask', s: 'd', ut: 3.7 }] },
  { slot: 'Bartender Pkg - British', cat: 'British Styles', drunk: false, m: [] },
  { slot: 'Pale Lukr Choice', cat: 'Pale Lager', drunk: true, m: [] },
  { slot: 'Special Event Pale Lager', cat: 'Pale Lager', drunk: false, m: [{ n: 'Flensburger Pilsener', b: 'Flensburger', abv: '4.8%', sz: '.4 L', p: '$9.00', note: 'Northern German pils on draft', s: 'd', ut: 3.3 }, { n: 'Birrificio Italiano Tipopils', b: 'Birr. Italiano', abv: '5.2%', sz: '.3 L', p: '$9.50', note: 'Italian pils on draft', s: 'd', ut: 3.9 }, { n: 'St. Georgen Kellerbier', b: 'St. Georgen', abv: '4.9%', sz: '.5 L', p: '$9.50', note: 'Franconian lager on draft', s: 'd', ut: 3.6 }] },
  { slot: 'Stichfass Cask Pour', cat: 'Pale Lager', drunk: false, m: [] },
  { slot: 'Bartender Draft - Pale Lager', cat: 'Pale Lager', drunk: false, m: [{ n: 'Flensburger Pilsener', b: 'Flensburger', abv: '4.8%', sz: '.4 L', p: '$9.00', note: 'Northern German pils draft', s: 'd', ut: 3.3 }] },
  { slot: 'Bartender Pkg - Pale Lager', cat: 'Pale Lager', drunk: false, m: [] },
  { slot: 'Bartender Draft - Dark Lager', cat: 'Dark Lager', drunk: false, m: [{ n: 'Schilling Jelen 15', b: 'Schilling', abv: '6.0%', sz: '.5 L', p: '$10.00', note: 'Czech dark special on draft', s: 'd', ut: 3.8 }, { n: 'Pohjala Must Kuld', b: 'Pohjala', abv: '7.8%', sz: '8 oz', p: '$10.00', note: 'Baltic porter on draft', s: 'd', ut: 3.9 }] },
  { slot: 'Special Event Bock', cat: 'Bock Beers', drunk: true, m: [] },
  { slot: 'Grodziskie Choice', cat: 'Smokebeers', drunk: false, m: [{ n: 'Schlenkerla Fastenbier', b: 'Schlenkerla', abv: '5.9%', sz: '.5 L', p: '$10.00', note: 'Beechwood smoked lager draft', s: 'd', ut: 3.7 }] },
  { slot: 'Special Event Smokebier', cat: 'Smokebeers', drunk: true, m: [] },
  { slot: 'Bartender Pkg - Belgian Saison', cat: 'Belgian Saison', drunk: false, m: [] },
  { slot: 'Bartender Draft - Farmhouse', cat: 'Belgian Farmhouse', drunk: false, m: [{ n: 'Au Baron/JK Noblesse Oblige', b: 'Au Baron/Jester King', abv: '4.7%', sz: '8 oz', p: '$10.50', note: 'Honey saison on draft', s: 'd', ut: 3.8 }] },
  { slot: 'Bartender Pkg - Farmhouse', cat: 'Belgian Farmhouse', drunk: false, m: [] },
  { slot: 'Belgian Blonde Choice', cat: 'Belgian Blonde/Pale', drunk: true, m: [] },
  { slot: 'Oud Beersel Choice', cat: 'Belgian Lambic', drunk: true, m: [] },
  { slot: 'Boon Geuze Choice', cat: 'Belgian Lambic', drunk: true, m: [{ n: 'Boon Geuze Selection (draft)', b: 'Boon', abv: '6.3%', sz: '8 oz', p: '$11.00', note: 'Draft gueuze from select foeders', s: 'd', ut: 4.0 }] },
  { slot: 'Tilquin Wine Grape Choice', cat: 'Belgian Lambic', drunk: false, m: [{ n: 'Tilquin Oude Pinot Gris', b: 'Tilquin', abv: '8.4%', sz: '750 ml', p: '$50', note: 'Lambic w/ Pinot Gris (bottle)', s: 'b', ut: 4.2 }, { n: 'Tilquin Oude Pinot Noir', b: 'Tilquin', abv: '7.7%', sz: '750 ml', p: '$50', note: 'Lambic w/ Pinot Noir (bottle)', s: 'b', ut: 4.3 }] },
  { slot: 'Cantillon Fruited Choice', cat: 'Belgian Lambic', drunk: false, m: [] },
  { slot: 'Special Event Lambic', cat: 'Belgian Lambic', drunk: false, m: [{ n: 'Tilquin Airelle Sauvage (draft)', b: 'Tilquin', abv: '5.1%', sz: '8 oz', p: '$11.00', note: 'Wild lingonberry lambic draft!', s: 'd', ut: 4.1 }] },
  { slot: 'Special Event Fruit Lambic', cat: 'Belgian Lambic', drunk: false, m: [{ n: 'Tilquin Airelle Sauvage', b: 'Tilquin', abv: '5.1%', sz: '8 oz', p: '$11.00', note: 'Wild lingonberry lambic draft!', s: 'd', ut: 4.1 }, { n: 'Drie Fonteinen Kweeper', b: '3 Fonteinen', abv: '5.9%', sz: '750 ml', p: '$65', note: 'Quince lambic (bottle)', s: 'b', ut: 4.3 }] },
  { slot: 'Bartender Draft - Lambic', cat: 'Belgian Lambic', drunk: false, m: [{ n: 'Boon Geuze Selection', b: 'Boon', abv: '6.3%', sz: '8 oz', p: '$11.00', note: 'Draft gueuze', s: 'd', ut: 4.0 }, { n: 'Tilquin Airelle Sauvage', b: 'Tilquin', abv: '5.1%', sz: '8 oz', p: '$11.00', note: 'Wild lingonberry draft', s: 'd', ut: 4.1 }] },
  { slot: 'Bartender Pkg - Lambic', cat: 'Belgian Lambic', drunk: false, m: [] },
  { slot: 'Special Event Mixed Ferm', cat: 'Mixed Fermentation', drunk: false, m: [{ n: 'Liquid Riot L.R.V. Blend 3', b: 'Liquid Riot', abv: '6.0%', sz: '12 oz', p: '$9.00', note: 'American spontaneous draft', s: 'd', ut: 3.9 }] },
  { slot: 'Bartender Draft - Mixed Ferm', cat: 'Mixed Fermentation', drunk: false, m: [{ n: 'Liquid Riot L.R.V. Blend 3', b: 'Liquid Riot', abv: '6.0%', sz: '12 oz', p: '$9.00', note: 'American spontaneous draft', s: 'd', ut: 3.9 }] },
  { slot: 'Bartender Pkg - Mixed Ferm', cat: 'Mixed Fermentation', drunk: false, m: [{ n: 'Russian River Temptation', b: 'Russian River', abv: '7.5%', sz: '375 ml', p: '$25', note: 'Brett Chardonnay (bottle)', s: 'b', ut: 4.1 }, { n: 'Russian River Supplication', b: 'Russian River', abv: '7.5%', sz: '375 ml', p: '$25', note: 'Mixed-ferm cherries (bottle)', s: 'b', ut: 4.2 }, { n: 'Russian River Beatification', b: 'Russian River', abv: '6.0%', sz: '375 ml', p: '$25', note: 'Spontaneous ale (bottle)', s: 'b', ut: 4.4 }] },
  { slot: 'Fonta Flora Fruit Choice', cat: 'Fruit Beers', drunk: false, m: [] },
  { slot: 'Oxbow Wine Grape Choice', cat: 'Fruit Beers', drunk: false, m: [{ n: 'Oxbow Blue Noir', b: 'Oxbow', abv: '7.0%', sz: '500 ml', p: '$25', note: 'Blueberry + Pinot Noir (bottle)', s: 'b', ut: 3.9 }] },
  { slot: 'Special Event Fruited', cat: 'Fruit Beers', drunk: false, m: [{ n: 'Allagash Coolship Red (draft)', b: 'Allagash', abv: '5.6%', sz: '8 oz', p: '$10.50', note: 'Spontaneous framboise draft!', s: 'd', ut: 4.2 }, { n: 'Koelbus Apricot (draft)', b: 'Koelbus', abv: '6.5%', sz: '8 oz', p: '$9.50', note: 'Spontaneous apricot draft', s: 'd', ut: 4.0 }] },
  { slot: 'Bartender Draft - Fruit Beer', cat: 'Fruit Beers', drunk: true, m: [] },
  { slot: 'Bartender Pkg - Fruit Beer', cat: 'Fruit Beers', drunk: false, m: [] },
  { slot: 'English Cider Choice', cat: 'Cider', drunk: true, m: [] },
  { slot: 'Spanish Cider Choice', cat: 'Cider', drunk: false, m: [] },
  { slot: 'French Cider Choice', cat: 'Cider', drunk: false, m: [] },
  { slot: 'American Cider', cat: 'Cider', drunk: true, m: [] },
  { slot: 'Choice Cider / Wine Hybrid', cat: 'Cider', drunk: false, m: [] },
  { slot: 'Milko Tube Choice', cat: 'Culturally Important', drunk: true, m: [] },
  { slot: 'Vault Pick Choice', cat: 'Culturally Important', drunk: false, m: [] },
  { slot: 'Mass Choice', cat: 'Culturally Important', drunk: false, m: [] },
  { slot: 'Staff Choice', cat: 'Culturally Important', drunk: false, m: [] },
];