// NOVARE RES CHALICE TRACKER DATA
// Drunk count: 99 at Novare (matches Chalice tab total; 75 named + 24 choices)
// Draft: 7/8/26 | Bottle: 7/6/26 | Last updated: 7/9/26

window.DRAFT_URL = 'https://novareresbiercafe.com/wp-content/uploads/draught.pdf';
window.BOTTLE_URL = 'https://novareresbiercafe.com/wp-content/uploads/bottlelist.pdf';
window.DRAFT_DATE = '7/8/26';
window.BOTTLE_DATE = '7/6/26';
window.SHEET_DATE = '7/9/26';

// Beers first seen on the bottle list within the last 30 days get a NEW badge
// Format: { 'beer id': '2026-MM-DD' } - first appearance date
window.BOTTLE_FIRST_SEEN = {
  // Carried over from 4/01/26 tracker
  'sam smith nut brown ale': '2026-04-01',
  'sam smith taddy porter': '2026-04-01',
  'bissell angels series': '2026-04-01',
  'harviestoun old engine oil': '2026-04-01',
  'de struise choice': '2026-04-01',
  'maine beer peeper': '2026-04-01',
  'northcoast old stock': '2026-04-01',
  'j.w.lees harvest ale': '2026-04-01',
  'de struise clash of the titans': '2026-04-01',
  'tynt meadow dark english': '2026-04-01',
  'st peters english ale': '2026-04-01',
  'ettaler edel hell': '2026-04-01',
  'schlenkerla rauch helles': '2026-04-01',
  'schlenkerla weizen': '2026-04-01',
  'schneider aventinus': '2026-04-01',
  'lemke berliner woodruff': '2026-04-01',
  'unibroue la fin du monde': '2026-04-01',
  'chimay cing cents white': '2026-04-01',
  'st bernardus pater 6': '2026-04-01',
  'westmalle dubbel': '2026-04-01',
  'rochefort 6': '2026-04-01',
  'chimay premiere red': '2026-04-01',
  'st bernardus prior 8': '2026-04-01',
  'st bernardus abt 12': '2026-04-01',
  'rochefort 8': '2026-04-01',
  'rodenbach grand cru': '2026-04-01',
  'dupont saison': '2026-04-01',
  'oude orval': '2026-04-01',
  'dupont avec les bons voeux': '2026-04-01',
  'drie fonteinen a & g': '2026-04-01',
  'tilquin gueze': '2026-04-01',
  'drie fonteinen kriek': '2026-04-01',
  'oxbow native/wild series': '2026-04-01',
  'allagash coolship red': '2026-04-01',
  // NEW on 5/13/26 bottle list
  'pilsner urquell': '2026-05-13',
  'allagash cellars #10': '2026-05-13',
  'allagash cellars #13': '2026-05-13',
  'de la senne quintessence': '2026-05-13',
  'ridgeway russian imperial stout': '2026-05-13',
  'de dolle boskeun passbier': '2026-05-13',
  'de struise pannepot grand reserva': '2026-05-13',
  'orange bike guava sour': '2026-05-13',
  // NEW on 5/15/26 bottle list
  'schneider weisse': '2026-05-15',
  'oxbow fifteen years cuvee': '2026-05-15',
  'long trail ale': '2026-05-15',
  // NEW on 6/25/26 bottle list
  'north coast old rasputin': '2026-06-25',
  'cushnoc rust bucket red': '2026-06-25',
  'italiano tipopils': '2026-06-25',
  'marshall wharf sexy chaos': '2026-06-25',
  'coniston bluebird bitter': '2026-06-25',
  // NEW on 7/6/26 bottle list
  'de glazen toren ondineke': '2026-07-06',
  'banhof leipzig gose': '2026-07-06',
};

window.BEERS = [
  { id: 'bunker libbytown brown', drunk: true },
  { id: 'barreled souls east brown & down', drunk: false },
  { id: 'sam smith nut brown ale', drunk: true },
  { id: 'sam smith taddy porter', drunk: true, bottle: { brewery: 'Sam Smith', style: 'English Porter', abvNum: 5.0, abv: '5.0%', sz: '14.9 oz', price: '$10', ut: 3.6 } },
  { id: 'deschutes black butte', drunk: true, bottle: { brewery: 'Deschutes', style: 'American Porter', abvNum: 5.5, abv: '5.5%', sz: '12 oz', price: '$7', ut: 3.7 } },
  { id: 'mayflower porter', drunk: false },
  { id: 'nogne o porter', drunk: false },
  { id: 'jacks abby framinghammer series', drunk: false },
  { id: 'bissell angels series', drunk: false, bottle: { brewery: 'Bissell Brothers', style: 'BA Imperial Porter', abvNum: 12.8, abv: '12.8%', sz: '500 ml', price: '$30', ut: 4.3 } },
  { id: 'sam smith oatmeal stout', drunk: true, bottle: { brewery: 'Sam Smith', style: 'Oatmeal Stout', abvNum: 5.0, abv: '5.0%', sz: '550 ml', price: '$10', ut: 3.7 } },
  { id: 'oharas irish stout', drunk: false },
  { id: 'lake st george oatmeal stout', drunk: true },
  { id: 'harviestoun old engine oil', drunk: true, bottle: { brewery: 'Harviestoun', style: 'Scottish Craft Stout', abvNum: 6.0, abv: '6.0%', sz: '12 oz', price: '$9', ut: 3.6 } },
  { id: 'maine beer mean old tom', drunk: true },
  { id: 'north coast old rasputin', drunk: true, bottle: { brewery: 'North Coast', style: 'Russian Imperial Stout', abvNum: 9.0, abv: '9.0%', sz: '355 ml', price: '$8', ut: 4.0 } },
  { id: 'dieu du ciel peche mortel', drunk: true, draft: { brewery: 'Dieu du Ciel!', style: 'Imperial Coffee Stout (Nitro)', abvNum: 9.5, abv: '9.5%', sz: '8 oz', price: '$10.00', ut: 4.3 } },
  { id: 'tributary mott the lesser', drunk: false },
  { id: 'barreled souls stay puft series', drunk: true },
  { id: 'marshall wharf sexy chaos', drunk: false, bottle: { brewery: 'Marshall Wharf', style: 'Russian Imperial Stout', abvNum: 10.7, abv: '10.7%', sz: '16 oz', price: '$10', ut: 4.0 } },
  { id: 'prairie bomb series', drunk: true },
  { id: 'lrbc straight to black:out', drunk: true, bottle: { brewery: 'Liquid Riot', style: 'BA Imperial Stout (Oat)', abvNum: 13.0, abv: '13.0%', sz: '500 ml', price: '$22', ut: 4.2 } },
  { id: 'pohjala pime oo series', drunk: false },
  { id: 'bissell sigil series', drunk: false },
  { id: 'de struise choice', drunk: true, bottle: { brewery: 'De Struise', style: 'BA Imperial Stout (Black Damnation)', abvNum: 13.0, abv: '13.0%', sz: '330 ml', price: '$15', ut: 3.9 } },
  { id: 'sierra nevada pale', drunk: true },
  { id: 'maine beer peeper', drunk: true, bottle: { brewery: 'Maine Beer Co.', style: 'American Pale Ale', abvNum: 5.5, abv: '5.5%', sz: '500 ml', price: '$10', ut: 3.9 } },
  { id: 'dogfish head 30 min', drunk: true, bottle: { brewery: 'Dogfish Head', style: 'Session IPA', abvNum: 4.0, abv: '4.0%', sz: '12 oz', price: '$6', ut: 3.5 } },
  { id: 'tributary pale', drunk: true },
  { id: 'mast landing dh tell tale', drunk: false },
  { id: 'bissell brothers lux', drunk: false },
  { id: 'trillium fort point pale', drunk: true },
  { id: 'maine beer dinner', drunk: false },
  { id: 'sierra nevada celebration', drunk: true },
  { id: 'russian river pliny the elder', drunk: true, draft: { brewery: 'Russian River', style: 'Double IPA', abvNum: 8.0, abv: '8.0%', sz: '12 oz', price: '$9.50', ut: 4.1 } },
  { id: 'boothbay thirsty botanist', drunk: true },
  { id: 'orono the way life should be', drunk: false },
  { id: 'bissell brothers swish', drunk: false },
  { id: 'mast landing pantless thunder', drunk: true },
  { id: 'battery steele flume squared', drunk: false },
  { id: 'goodfire ddh prime', drunk: false },
  { id: 'northcoast old stock', drunk: false, bottle: { brewery: 'North Coast', style: 'British Barleywine', abvNum: 12.5, abv: '12.5%', sz: '355 ml', price: '$8', ut: 3.9 } },
  { id: 'j.w.lees harvest ale', drunk: false, bottle: { brewery: 'J.W. Lees', style: 'English Barley Wine', abvNum: 11.5, abv: '11.5%', sz: '220 ml', price: '$12', ut: 3.9 } },
  { id: 'de struise clash of the titans', drunk: false, bottle: { brewery: 'De Struise', style: 'BA Barleywine (Grand Reserva)', abvNum: 12.6, abv: '12.6%', sz: '330 ml', price: '$15', ut: 4.1 } },
  { id: 'sierra nevada big foot', drunk: false },
  { id: 'coniston bluebird bitter', drunk: true, bottle: { brewery: 'Coniston', style: 'English Bitter', abvNum: 3.8, abv: '3.8%', sz: '500 ml', price: '$11', ut: 3.7 } },
  { id: 'green king old speckled hen', drunk: true },
  { id: 'lake st george diver pale', drunk: false },
  { id: 'ridgeway esb', drunk: true },
  { id: 'tynt meadow dark english', drunk: false },
  { id: 'tributary esb', drunk: false },
  { id: 'st peters english ale', drunk: false },
  { id: 'barreled souls munro', drunk: true },
  { id: 'cushnoc rust bucket red', drunk: true, bottle: { brewery: 'Cushnoc', style: 'American Amber', abvNum: 4.9, abv: '4.9%', sz: '16 oz', price: '$9', ut: 3.8 } },
  { id: 'ettaler edel hell', drunk: false },
  { id: 'hofbrau original', drunk: true },
  { id: 'jacks abby house lager', drunk: false },
  { id: 'von trapp boho pils', drunk: false },
  { id: 'pilsner urquell', drunk: true, bottle: { brewery: 'Pilsner Urquell', style: 'Czech Pilsner', abvNum: 4.4, abv: '4.4%', sz: '16.9 oz', price: '$6', ut: 3.8 } },
  { id: 'schilling palmovka 12', drunk: false },
  { id: 'czechvar original', drunk: true },
  { id: 'sacred profane pale lager', drunk: false },
  { id: 'einbecker brauherren pils', drunk: false },
  { id: 'ayinger bairisch pils', drunk: true },
  { id: 'flensberger pils', drunk: false },
  { id: 'italiano tipopils', drunk: true, bottle: { brewery: 'Birrificio Italiano', style: 'Italian Pilsner', abvNum: 5.2, abv: '5.2%', sz: '330 ml', price: '$9', ut: 3.8 } },
  { id: 'human robot hallertau pils', drunk: false },
  { id: 'sacred profane amber lager', drunk: false },
  { id: 'schilling petrin 11', drunk: false },
  { id: 'st georgenbrau kellerbier', drunk: false },
  { id: 'von trapp vienna', drunk: false },
  { id: 'oec coolship black lager', drunk: true },
  { id: 'ayinger dunkel', drunk: false },
  { id: 'schilling modernism', drunk: true },
  { id: 'sacred profane dark lager', drunk: true },
  { id: 'ettaller hellerbock', drunk: true },
  { id: 'einbecker winterbock', drunk: false },
  { id: 'ayinger celebrator', drunk: true, bottle: { brewery: 'Ayinger', style: 'Doppelbock', abvNum: 6.7, abv: '6.7%', sz: '330 ml', price: '$9', ut: 3.9 } },
  { id: 'weihenstephan korbinian', drunk: true, bottle: { brewery: 'Weihenstephan', style: 'Doppelbock', abvNum: 7.4, abv: '7.4%', sz: '500 ml', price: '$9', ut: 3.9 } },
  { id: 'samichlaus vintage', drunk: false },
  { id: 'schlenkerla rauch helles', drunk: false, bottle: { brewery: 'Schlenkerla', style: 'Rauch Helles', abvNum: 4.3, abv: '4.3%', sz: '16 oz', price: '$9', ut: 3.5 } },
  { id: 'schlenkerla maerzen', drunk: false, bottle: { brewery: 'Schlenkerla', style: 'Rauch Marzen', abvNum: 5.1, abv: '5.1%', sz: '500 ml', price: '$9', ut: 3.9 } },
  { id: 'sacred profane smoked dark lager', drunk: true },
  { id: 'ayinger brau-weisse', drunk: true, bottle: { brewery: 'Ayinger', style: 'German Hefeweizen', abvNum: 5.1, abv: '5.1%', sz: '330 ml', price: '$9', ut: 3.7 } },
  { id: 'schneider weisse', drunk: false, bottle: { brewery: 'Schneider', style: 'German Hefeweizen', abvNum: 5.4, abv: '5.4%', sz: '500 ml', price: '$9', ut: 3.7 } },
  { id: 'plank weissbier', drunk: true },
  { id: 'schlenkerla weizen', drunk: false, bottle: { brewery: 'Schlenkerla', style: 'Smoked Wheat Beer', abvNum: 5.2, abv: '5.2%', sz: '500 ml', price: '$9', ut: 3.6 } },
  { id: 'weihenstephan vitus', drunk: true, bottle: { brewery: 'Weihenstephan', style: 'Weizenbock', abvNum: 7.7, abv: '7.7%', sz: '500 ml', price: '$9', ut: 4.0 } },
  { id: 'schneider aventinus', drunk: true, bottle: { brewery: 'Schneider', style: 'Dunkelweizen Doppelbock', abvNum: 8.0, abv: '8.0%', sz: '500 ml', price: '$10', ut: 4.0 } },
  { id: 'lemke berliner woodruff', drunk: false, bottle: { brewery: 'Lemke', style: 'Berliner Weisse (Waldmeister)', abvNum: 4.0, abv: '4.0%', sz: '12 oz', price: '$10', ut: 3.5 } },
  { id: 'prof fritz briem 1809 berliner', drunk: false },
  { id: 'banhof leipzig gose', drunk: false, bottle: { brewery: 'Bayerischer Bahnhof', style: 'Leipziger Gose', abvNum: 4.6, abv: '4.6%', sz: '12 oz', price: '$9', ut: 3.6 } },
  { id: 'ritterguts gose', drunk: true },
  { id: 'fruh kolsch', drunk: true, draft: { brewery: 'Fruh', style: 'Kolsch', abvNum: 4.8, abv: '4.8%', sz: '.4 L', price: '$9.00', ut: 3.6 } },
  { id: 'gaffel kolsch', drunk: true, bottle: { brewery: 'Gaffel', style: 'German Kolsch', abvNum: 4.8, abv: '4.8%', sz: '16.9 oz', price: '$9', ut: 3.5 } },
  { id: 'reissdorf kolsch', drunk: true, bottle: { brewery: 'Reissdorf', style: 'German Kolsch', abvNum: 4.8, abv: '4.8%', sz: '16.9 oz', price: '$8', ut: 3.6 } },
  { id: 'uerige alt', drunk: false },
  { id: 'westmalle extra', drunk: true },
  { id: 'st. bernardus extra 4', drunk: true, bottle: { brewery: 'St Bernardus', style: 'Abbey Single', abvNum: 4.8, abv: '4.8%', sz: '330 ml', price: '$9', ut: 3.5 } },
  { id: 'chimay doree gold', drunk: true },
  { id: 'val dieu blonde', drunk: false },
  { id: 'cuvee de trolls', drunk: false },
  { id: 'allagash curieux', drunk: true },
  { id: 'piraat', drunk: true },
  { id: 'de dolle dulle teve', drunk: true },
  { id: 'de dolle stille nacht', drunk: false },
  { id: 'de glazen toren ondineke', drunk: false, bottle: { brewery: 'De Glazen Toren', style: 'Belgian Tripel', abvNum: 8.5, abv: '8.5%', sz: '750 ml', price: '$22', ut: 3.7 } },
  { id: 'st bernardus tripel', drunk: true },
  { id: 'unibroue la fin du monde', drunk: true, bottle: { brewery: 'Unibroue', style: 'Belgian Tripel', abvNum: 9.0, abv: '9.0%', sz: '12 oz', price: '$9', ut: 4.0 } },
  { id: 'de garre tripel', drunk: true },
  { id: 'duvel golden strong', drunk: false, draft: { brewery: 'Duvel', style: 'DH Belgian Golden Strong (6.66)', abvNum: 6.66, abv: '6.66%', sz: '12 oz', price: '$10.00', ut: 3.9 }, bottle: { brewery: 'Duvel', style: 'Belgian Golden Strong', abvNum: 8.5, abv: '8.5%', sz: '330 ml', price: '$9', ut: 4.0 } },
  { id: 'westmalle trippel', drunk: false },
  { id: 'chimay cing cents white', drunk: false, bottle: { brewery: 'Chimay', style: 'Trappist Tripel (White/Cinq Cents)', abvNum: 8.0, abv: '8.0%', sz: '330 ml', price: '$12', ut: 3.8 } },
  { id: 'chimay cent cinquante green', drunk: true, bottle: { brewery: 'Chimay', style: 'Trappist Golden Strong (Green/150)', abvNum: 10.0, abv: '10.0%', sz: '330 ml', price: '$12', ut: 4.2 } },
  { id: 'st bernardus pater 6', drunk: false, bottle: { brewery: 'St Bernardus', style: 'Abbey Dubbel', abvNum: 6.7, abv: '6.7%', sz: '330 ml', price: '$9', ut: 3.7 } },
  { id: 'westmalle dubbel', drunk: true, bottle: { brewery: 'Westmalle', style: 'Trappist Dubbel', abvNum: 7.0, abv: '7.0%', sz: '330 ml', price: '$10', ut: 3.9 } },
  { id: 'rochefort 6', drunk: false, bottle: { brewery: 'Rochefort', style: 'Trappist Dubbel', abvNum: 7.5, abv: '7.5%', sz: '330 ml', price: '$11', ut: 3.8 } },
  { id: 'allagash foliage report', drunk: false },
  { id: 'chimay premiere red', drunk: false, bottle: { brewery: 'Chimay', style: 'Trappist Dubbel (Red/Première)', abvNum: 7.0, abv: '7.0%', sz: '330 ml', price: '$11', ut: 3.7 } },
  { id: 'achel brune', drunk: true },
  { id: 'st bernardus prior 8', drunk: false, bottle: { brewery: 'St Bernardus', style: 'Strong Dubbel', abvNum: 8.0, abv: '8.0%', sz: '330 ml', price: '$9', ut: 4.0 } },
  { id: 'chimay grand reserve blue', drunk: false, draft: { brewery: 'Chimay', style: 'Trappist Strong Dark (Blue/ATP)', abvNum: 9.0, abv: '9.0%', sz: '10 oz', price: '$11.50', ut: 4.4 }, bottle: { brewery: 'Chimay', style: 'Trappist Strong Dark (Blue)', abvNum: 9.0, abv: '9.0%', sz: '330 ml', price: '$12', ut: 4.3 } },
  { id: 'st bernardus abt 12', drunk: false, bottle: { brewery: 'St Bernardus', style: 'Belgian Dark Strong', abvNum: 10.5, abv: '10.5%', sz: '330 ml', price: '$10', ut: 4.3 } },
  { id: 'rochefort 8', drunk: false, bottle: { brewery: 'Rochefort', style: 'Trappist Dark Ale', abvNum: 9.2, abv: '9.2%', sz: '330 ml', price: '$11', ut: 4.2 } },
  { id: 'rochefort 10', drunk: false },
  { id: 'de struise pannepot', drunk: true },
  { id: 'ommegang three philosophers', drunk: true },
  { id: 'rodenbach dogfish crison cru', drunk: false },
  { id: 'rodenbach grand cru', drunk: false, bottle: { brewery: 'Rodenbach', style: 'Flemish Red-Brown', abvNum: 6.0, abv: '6.0%', sz: '330 ml', price: '$9', ut: 3.9 } },
  { id: 'monks sour red', drunk: false },
  { id: 'petrus 40/40/20', drunk: false },
  { id: 'de la senne ouden vat', drunk: false },
  { id: 'dupont saison', drunk: true, bottle: { brewery: 'Dupont', style: 'Saison', abvNum: 6.5, abv: '6.5%', sz: '375 ml', price: '$12', ut: 3.9 } },
  { id: 'de ranke xx bitter', drunk: false },
  { id: 'de la senne taras boulba', drunk: true },
  { id: 'kazematten saison', drunk: false },
  { id: 'de glazen toren saison', drunk: false },
  { id: 'oxbow loretta grisette', drunk: true },
  { id: 'oude orval', drunk: true, bottle: { brewery: 'Orval', style: 'Trappist Ale (Aged)', abvNum: 6.9, abv: '6.9%', sz: '330 ml', price: '$12', ut: 4.1 } },
  { id: 'dupont avec les bons voeux', drunk: true, bottle: { brewery: 'Dupont', style: 'Strong Saison', abvNum: 9.5, abv: '9.5%', sz: '375 ml', price: '$14', ut: 4.1 } },
  { id: 'thiriez ambre', drunk: false },
  { id: 'ommegang hennepin', drunk: false },
  { id: 'allagash white', drunk: true, bottle: { brewery: 'Allagash', style: 'Belgian Witte', abvNum: 5.0, abv: '5.0%', sz: '16 oz', price: '$7', ut: 3.8 } },
  { id: 'st. bernardus witbier', drunk: true, bottle: { brewery: 'St Bernardus', style: 'Belgian Witbier', abvNum: 5.5, abv: '5.5%', sz: '11.2 oz', price: '$9', ut: 3.6 } },
  { id: 'hitachino nest white', drunk: true, bottle: { brewery: 'Hitachino Nest', style: 'Belgian Witte', abvNum: 5.5, abv: '5.5%', sz: '11.8 oz', price: '$9', ut: 3.7 } },
  { id: 'unibroue blanche de chambly', drunk: false },
  { id: 'drie fonteinen a & g', drunk: false, bottle: { brewery: 'Drie Fonteinen', style: "Gueuze (Cuvée A&G '18)", abvNum: 6.2, abv: '6.2%', sz: '375 ml', price: '$25', ut: 4.4 } },
  { id: 'tilquin gueze', drunk: false, bottle: { brewery: 'Tilquin', style: 'Oude Gueuze', abvNum: 7.0, abv: '7.0%', sz: '375 ml', price: '$22', ut: 4.2 } },
  { id: 'timmermans gueuze', drunk: false },
  { id: 'girardin gueuze', drunk: true, bottle: { brewery: 'Girardin', style: 'Gueuze (1882 Black Label)', abvNum: 5.0, abv: '5.0%', sz: '375 ml', price: '$20', ut: 4.3 } },
  { id: 'drie fonteinen kriek', drunk: false, bottle: { brewery: 'Drie Fonteinen', style: 'Oude Kriek (Kelleris)', abvNum: 5.9, abv: '5.9%', sz: '750 ml', price: '$75', ut: 4.5 } },
  { id: 'allagash coolship resurgem', drunk: false },
  { id: 'oxbow native/wild series', drunk: false, bottle: { brewery: 'Oxbow', style: "Spontaneous Farmhouse ('16/'17)", abvNum: 6.0, abv: '6.0%', sz: '750 ml', price: '$45', ut: 4.0 } },
  { id: 'russian river tion series', drunk: true, bottle: { brewery: 'Russian River', style: 'Sour Dark Ale (Consecration)', abvNum: 10.0, abv: '10.0%', sz: '375 ml', price: '$25', ut: 4.2 } },
  { id: 'jester king petite prince', drunk: false },
  { id: 'plan bee barn beer', drunk: false },
  { id: 'allagash coolship red', drunk: true, bottle: { brewery: 'Allagash', style: 'Spontaneous Framboise', abvNum: 5.6, abv: '5.6%', sz: '375 ml', price: '$25', ut: 4.2 } },
  { id: 'jester king atrial rubicite', drunk: false },
  { id: 'koelbus apricot', drunk: true, bottle: { brewery: 'Koelbus', style: 'Fruited Spontaneous', abvNum: 6.5, abv: '6.5%', sz: '750 ml', price: '$40', ut: 3.5 } },
  { id: 'underberg', drunk: true },
  { id: 'fernet michaud', drunk: false },
  { id: 'anything from a porron', drunk: false },
];

window.ALL_CHOICES = [
  { slot: 'Brown Ale Choice', cat: 'Brown', drunk: false, m: [] },
  { slot: 'Nitro Stout Choice', cat: 'Stout', drunk: false, m: [{ n: "Sullivan's Black Marble Stout (Nitro)", b: "Sullivan's", abv: '5.1%', sz: '16 oz', p: '$9.50', note: 'Traditional Irish dry stout on nitro', s: 'd', ut: 3.8 }, { n: 'Dieu du Ciel! Péché Mortel (Nitro)', b: 'Dieu du Ciel!', abv: '9.5%', sz: '8 oz', p: '$10.00', note: 'Imperial coffee stout on nitro', s: 'd', ut: 4.3 }] },
  { slot: 'Oyster Stout Choice', cat: 'Stout', drunk: false, m: [] },
  { slot: 'Special Event Imperial Stout', cat: 'Imperial Stout', drunk: true, m: [] },
  { slot: 'Bartender Draft - Imp. Stout', cat: 'Imperial Stout', drunk: true, m: [{ n: 'Dieu du Ciel! Péché Mortel (Nitro)', b: 'Dieu du Ciel!', abv: '9.5%', sz: '8 oz', p: '$10.00', note: 'Imperial coffee stout on nitro', s: 'd', ut: 4.3 }] },
  { slot: 'Bartender Pkg - Imp. Stout', cat: 'Imperial Stout', drunk: false, m: [{ n: 'North Coast Old Rasputin', b: 'North Coast', abv: '9.0%', sz: '355 ml', p: '$8', note: 'Russian imperial stout (bottle)', s: 'b', ut: 4.0 }, { n: 'Omnipollo/Dugges NOA Pecan Mud Cake', b: 'Omnipollo/Dugges', abv: '11.0%', sz: '330 ml', p: '$17', note: 'Pastry stout w/ pecans + chocolate', s: 'b', ut: 4.2 }] },
  { slot: 'California Common Choice', cat: 'American Retro', drunk: false, m: [] },
  { slot: 'Cream Ale Choice', cat: 'American Retro', drunk: false, m: [{ n: 'Genesee Cream Ale', b: 'Genesee', abv: '5.1%', sz: '12 oz', p: '$5', note: 'OG American cream ale (bottle)', s: 'b', ut: 3.2 }] },
  { slot: 'American Porter Choice', cat: 'American Retro', drunk: false, m: [{ n: 'Deschutes Black Butte Porter', b: 'Deschutes', abv: '5.5%', sz: '12 oz', p: '$7', note: 'Classic American porter (bottle)', s: 'b', ut: 3.7 }] },
  { slot: 'Pre-Prohibition Lager Choice', cat: 'American Retro', drunk: false, m: [] },
  { slot: 'American Amber Ale Choice', cat: 'American Retro', drunk: false, m: [{ n: 'Cushnoc Rust Bucket', b: 'Cushnoc', abv: '4.9%', sz: '16 oz', p: '$9', note: 'Maine amber ale (bottle)', s: 'b', ut: 3.8 }] },
  { slot: 'Special Event Pale Ale', cat: 'American Pale', drunk: false, m: [{ n: 'Orono Wicked Blueberry', b: 'Orono', abv: '5.0%', sz: '16 oz', p: '$9.00', note: 'Fruited American blonde w/ Maine blueberries', s: 'd', ut: 3.8 }] },
  { slot: 'Bartender Draft - Pale Ale', cat: 'American Pale', drunk: false, m: [{ n: 'Bissell Brothers Baby Genius', b: 'Bissell Bros', abv: '4.0%', sz: '16 oz', p: '$9.50', note: 'Extra hoppy hazy blonde (BBCH benefit)', s: 'd', ut: 3.8 }] },
  { slot: 'Bartender Pkg - Pale Ale', cat: 'American Pale', drunk: false, m: [] },
  { slot: 'Nebco Choice', cat: 'American IPA', drunk: false, m: [] },
  { slot: 'Wet Hop IPA Choice', cat: 'American IPA', drunk: false, m: [] },
  { slot: 'Special Event IPA', cat: 'American IPA', drunk: true, m: [{ n: 'Russian River DDH Pliny The Elder', b: 'Russian River', abv: '8.0%', sz: '12 oz', p: '$10.00', note: 'Double dry-hopped Pliny special release', s: 'd', ut: 4.1 }] },
  { slot: 'Bartender Draft - IPA', cat: 'American IPA', drunk: true, m: [{ n: 'Sierra Nevada West Ghost IPA', b: 'Sierra Nevada', abv: '7.2%', sz: '16 oz', p: '$9.50', note: 'West coast IPA on draft', s: 'd', ut: 3.9 }, { n: 'Russian River DDH Pliny The Elder', b: 'Russian River', abv: '8.0%', sz: '12 oz', p: '$10.00', note: 'DDH double IPA on draft', s: 'd', ut: 4.1 }] },
  { slot: 'Bartender Pkg - IPA', cat: 'American IPA', drunk: false, m: [{ n: 'Dogfish Head 90 Minute IPA', b: 'Dogfish Head', abv: '9.0%', sz: '12 oz', p: '$8', note: 'East coast DIPA (bottle)', s: 'b', ut: 4.0 }] },
  { slot: 'The Veil Choice', cat: 'Hazy IPA', drunk: false, m: [] },
  { slot: 'Modestman Choice', cat: 'Hazy IPA', drunk: true, m: [] },
  { slot: 'Other Half Choice', cat: 'Hazy IPA', drunk: true, m: [{ n: 'Other Half Broccoli', b: 'Other Half', abv: '7.9%', sz: '12 oz', p: '$10', note: 'DDH DIPA (bottle)', s: 'b', ut: 4.1 }] },
  { slot: 'Special Event Hazy IPA', cat: 'Hazy IPA', drunk: false, m: [{ n: 'Mast Landing/Messorem Beneath the Waves', b: 'Mast Landing', abv: '8.3%', sz: '12 oz', p: '$10.00', note: 'DDH DIPA w/ Motueka, El Dorado, Citra Cryo', s: 'd', ut: 4.2 }, { n: 'Le Ketch Dock 148', b: 'Le Ketch', abv: '6.5%', sz: '12 oz', p: '$10.50', note: 'NEIPA w/ Riwaka + tropical hops', s: 'd', ut: 4.0 }] },
  { slot: 'Bartender Draft - Hazy IPA', cat: 'Hazy IPA', drunk: true, m: [{ n: 'Le Ketch Dock 148', b: 'Le Ketch', abv: '6.5%', sz: '12 oz', p: '$10.50', note: 'NEIPA on draft', s: 'd', ut: 4.0 }] },
  { slot: 'Bartender Pkg - Hazy IPA', cat: 'Hazy IPA', drunk: false, m: [] },
  { slot: 'Barreled Souls Grain Wine', cat: 'Barley Wine', drunk: false, m: [{ n: 'Sebago Barrel-Aged Barleywine', b: 'Sebago', abv: '13.8%', sz: '12 oz', p: '$11', note: 'Bourbon BA barleywine (bottle)', s: 'b', ut: 4.0 }, { n: 'Thomas Hardy The Historical', b: 'Thomas Hardy', abv: '11.5%', sz: '250 ml', p: '$13', note: 'French oak-aged English BW, 1968 recipe', s: 'b', ut: 4.1 }] },
  { slot: 'Airline Choice (Scottish Nitro)', cat: 'British Styles', drunk: true, m: [] },
  { slot: 'Scotch Ale Choice', cat: 'British Styles', drunk: false, m: [] },
  { slot: 'Special Event Bitter/Mild', cat: 'British Styles', drunk: false, m: [{ n: 'Coniston Bluebird Bitter (Beer Engine!)', b: 'Coniston', abv: '3.6%', sz: '16 oz', p: '$10.00', note: 'Classic British bitter on cask', s: 'd', ut: 3.7 }] },
  { slot: 'British Cask Pour Choice', cat: 'British Styles', drunk: true, m: [{ n: 'Coniston Bluebird Bitter (Beer Engine!)', b: 'Coniston', abv: '3.6%', sz: '16 oz', p: '$10.00', note: 'British session bitter on cask!', s: 'd', ut: 3.7 }] },
  { slot: 'Bartender Draft - British', cat: 'British Styles', drunk: true, m: [{ n: 'Coniston Bluebird Bitter (Beer Engine!)', b: 'Coniston', abv: '3.6%', sz: '16 oz', p: '$10.00', note: 'British bitter on cask', s: 'd', ut: 3.7 }, { n: 'Tynt Meadow Blond (ATP)', b: 'Tynt Meadow', abv: '5.0%', sz: '12 oz', p: '$11.50', note: 'English blond ale by Trappist monks', s: 'd', ut: 3.9 }] },
  { slot: 'Bartender Pkg - British', cat: 'British Styles', drunk: false, m: [{ n: 'Ridgeway Russian Imperial Stout', b: 'Ridgeway', abv: '10.0%', sz: '330 ml', p: '$15', note: 'Russian imperial stout (bottle)', s: 'b', ut: 3.9 }, { n: 'Coniston Old Man Ale', b: 'Coniston', abv: '4.8%', sz: '500 ml', p: '$11', note: 'English brown ale (bottle)', s: 'b', ut: 3.7 }] },
  { slot: 'Pale Lukr Choice', cat: 'Pale Lager', drunk: true, m: [] },
  { slot: 'Special Event Pale Lager', cat: 'Pale Lager', drunk: true, m: [{ n: 'Bitburger Premium Pils', b: 'Bitburger', abv: '4.8%', sz: '.5 L', p: '$9.00', note: 'German pils, crisp and clean', s: 'd', ut: 3.6 }, { n: 'Pinkus Ur-Pils', b: 'Pinkus', abv: '5.2%', sz: '.3 L', p: '$9.50', note: 'Organic German pils, hop forward', s: 'd', ut: 3.7 }, { n: 'Dancing Gnome/Golden Age Czech 12°', b: 'Dancing Gnome/Golden Age', abv: '5.0%', sz: '.5 L', p: '$10.00', note: 'Collab bohemian pale lager, old-world crusher', s: 'd', ut: 3.8 }] },
  { slot: 'Stichfass Cask Pour', cat: 'Pale Lager', drunk: false, m: [] },
  { slot: 'Bartender Draft - Pale Lager', cat: 'Pale Lager', drunk: false, m: [{ n: 'Bitburger Premium Pils', b: 'Bitburger', abv: '4.8%', sz: '.5 L', p: '$9.00', note: 'German pils on draft', s: 'd', ut: 3.6 }, { n: 'Pinkus Ur-Pils', b: 'Pinkus', abv: '5.2%', sz: '.3 L', p: '$9.50', note: 'Organic German pils on draft', s: 'd', ut: 3.7 }, { n: 'Dancing Gnome/Golden Age Czech 12°', b: 'Dancing Gnome/Golden Age', abv: '5.0%', sz: '.5 L', p: '$10.00', note: 'Collab bohemian pale lager on draft', s: 'd', ut: 3.8 }] },
  { slot: 'Bartender Pkg - Pale Lager', cat: 'Pale Lager', drunk: false, m: [{ n: 'Rothaus Pils Tannenzäpfle', b: 'Rothaus', abv: '5.1%', sz: '355 ml', p: '$8', note: 'German pale lager from Black Forest', s: 'b', ut: 3.7 }, { n: 'Sapporo Premium Beer', b: 'Sapporo', abv: '4.9%', sz: '22 oz', p: '$9', note: 'Japanese rice lager', s: 'b', ut: 3.5 }, { n: 'Notch French Disko', b: 'Notch', abv: '4.9%', sz: '16 oz', p: '$9', note: 'French-style pils w/ Strisselspalt', s: 'b', ut: 3.7 }, { n: 'Jever Pils', b: 'Jever', abv: '4.8%', sz: '330 ml', p: '$6', note: 'German pils, 170-year recipe', s: 'b', ut: 3.7 }] },
  { slot: 'Bartender Draft - Dark Lager', cat: 'Dark Lager', drunk: false, m: [{ n: 'Schilling Pohoda 12°', b: 'Schilling', abv: '5.0%', sz: '.5 L', p: '$10.00', note: 'Czech-style dark lager (tmavy pivo)', s: 'd', ut: 3.8 }] },
  { slot: 'Special Event Bock', cat: 'Bock Beers', drunk: true, m: [{ n: 'Ayinger Maibock', b: 'Ayinger', abv: '6.8%', sz: '.5 L', p: '$10.00', note: 'World-class strong amber lager on draft', s: 'd', ut: 4.0 }] },
  { slot: 'Grodziskie Choice', cat: 'Smokebeers', drunk: false, m: [] },
  { slot: 'Special Event Smokebier', cat: 'Smokebeers', drunk: true, m: [{ n: 'Schlenkerla Oak Smoke', b: 'Schlenkerla', abv: '8.0%', sz: '500 ml', p: '$10', note: 'Rauch doppelbock w/ oak smoked malt', s: 'b', ut: 4.0 }, { n: 'Schlenkerla Urbock', b: 'Schlenkerla', abv: '6.6%', sz: '500 ml', p: '$9', note: 'Smoked bock aged in oakwood casks', s: 'b', ut: 3.9 }] },
  { slot: 'Bartender Pkg - Belgian Saison', cat: 'Belgian Saison', drunk: false, m: [{ n: "Blaugies Saison D'Epeautre", b: 'Blaugies', abv: '6.0%', sz: '750 ml', p: '$25', note: 'World-class spelt saison (bottle)', s: 'b', ut: 4.0 }] },
  { slot: 'Bartender Draft - Farmhouse', cat: 'Belgian Farmhouse', drunk: true, m: [{ n: 'Dupont Saison Dupont', b: 'Dupont', abv: '6.5%', sz: '12 oz', p: '$11.00', note: 'World-classic Belgian farmhouse on draft', s: 'd', ut: 3.9 }] },
  { slot: 'Bartender Pkg - Farmhouse', cat: 'Belgian Farmhouse', drunk: false, m: [{ n: "Blaugies Saison D'Epeautre", b: 'Blaugies', abv: '6.0%', sz: '750 ml', p: '$25', note: 'Benchmark spelt saison (bottle)', s: 'b', ut: 4.0 }, { n: 'Blaugies La Moneuse Special Noel', b: 'Blaugies', abv: '8.0%', sz: '750 ml', p: '$25', note: 'Biere de Noel, strong winter farmhouse', s: 'b', ut: 4.0 }] },
  { slot: 'Belgian Blonde Choice', cat: 'Belgian Blonde/Pale', drunk: true, m: [{ n: 'De Koninck Bolleke', b: 'De Koninck', abv: '5.2%', sz: '12 oz', p: '$10.00', note: 'Belgian pale ale, the beer of Antwerp', s: 'd', ut: 3.8 }, { n: 'De Dolle Arabier', b: 'De Dolle', abv: '8.0%', sz: '12 oz', p: '$10.50', note: 'Belgian blonde w/ Nugget + Whitbread hops', s: 'd', ut: 3.9 }, { n: 'Vedett Extra White', b: 'Vedett', abv: '4.7%', sz: '12 oz', p: '$9.00', note: 'Belgian wit w/ orange peel + coriander', s: 'd', ut: 3.5 }] },
  { slot: 'Oud Beersel Choice', cat: 'Belgian Lambic', drunk: true, m: [{ n: 'Oud Beersel Oude Geuze', b: 'Oud Beersel', abv: '6.0%', sz: '375 ml', p: '$25', note: 'Classic blended gueuze (bottle)', s: 'b', ut: 4.1 }, { n: "Oud Beersel Oude Geuze Barrel Selection Foeder '21", b: 'Oud Beersel', abv: '6.5%', sz: '375 ml', p: '$25', note: 'Limited white-wine foeder gueuze', s: 'b', ut: 4.2 }] },
  { slot: 'Boon Geuze Choice', cat: 'Belgian Lambic', drunk: true, m: [{ n: 'Boon Geuze Sélection (draft)', b: 'Boon', abv: '6.3%', sz: '8 oz', p: '$11.00', note: 'Foeder-select gueuze on draft', s: 'd', ut: 4.0 }, { n: 'Boon Geuze Mariage Parfait 2020', b: 'Boon', abv: '8.0%', sz: '375 ml', p: '$20', note: 'Best of vintage blended lambic (bottle)', s: 'b', ut: 4.3 }, { n: 'Boon Oude Geuze Black Label #4', b: 'Boon', abv: '7.0%', sz: '750 ml', p: '$30', note: 'Bone-dry anniversary blend (bottle)', s: 'b', ut: 4.2 }] },
  { slot: 'Tilquin Wine Grape Choice', cat: 'Belgian Lambic', drunk: false, m: [{ n: 'Tilquin Oude Pinot Gris', b: 'Tilquin', abv: '8.4%', sz: '750 ml', p: '$50', note: 'Lambic w/ Pinot Gris (bottle)', s: 'b', ut: 4.2 }, { n: 'Tilquin Oude Pinot Noir', b: 'Tilquin', abv: '7.7%', sz: '750 ml', p: '$50', note: 'Lambic w/ Pinot Noir (bottle)', s: 'b', ut: 4.3 }, { n: 'Tilquin Oude Riesling', b: 'Tilquin', abv: '8.4%', sz: '750 ml', p: '$50', note: 'Lambic w/ Riesling (bottle)', s: 'b', ut: 4.2 }, { n: 'Tilquin Oude Gewurztraminer', b: 'Tilquin', abv: '7.7%', sz: '750 ml', p: '$50', note: 'Lambic w/ Gewurztraminer (bottle)', s: 'b', ut: 4.2 }] },
  { slot: 'Cantillon Fruited Choice', cat: 'Belgian Lambic', drunk: true, m: [] },
  { slot: 'Special Event Lambic', cat: 'Belgian Lambic', drunk: true, m: [{ n: 'Boon Geuze Sélection (draft)', b: 'Boon', abv: '6.3%', sz: '8 oz', p: '$11.00', note: 'Foeder-select gueuze on draft', s: 'd', ut: 4.0 }, { n: 'Tilquin HORAL Mega Blend 2024', b: 'Tilquin', abv: '7.0%', sz: '750 ml', p: '$55', note: 'Blend of lambics from every HORAL member', s: 'b', ut: 4.4 }] },
  { slot: 'Special Event Fruit Lambic', cat: 'Belgian Lambic', drunk: false, m: [{ n: 'Tilquin Airelle Sauvage', b: 'Tilquin', abv: '5.1%', sz: '375 ml', p: '$28', note: 'Wild lingonberry lambic (bottle)', s: 'b', ut: 4.1 }, { n: 'Tilquin Oude Abricot', b: 'Tilquin', abv: '5.8%', sz: '375 ml', p: '$28', note: 'Apricot lambic (bottle)', s: 'b', ut: 4.2 }, { n: 'Drie Fonteinen Kweeper', b: '3 Fonteinen', abv: '5.9%', sz: '750 ml', p: '$65', note: 'Quince lambic (bottle)', s: 'b', ut: 4.3 }, { n: 'Tilquin Oude Mirabelle', b: 'Tilquin', abv: '7.0%', sz: '750 ml', p: '$65', note: 'Mirabelle golden plum lambic', s: 'b', ut: 4.3 }] },
  { slot: 'Bartender Draft - Lambic', cat: 'Belgian Lambic', drunk: false, m: [{ n: 'Boon Geuze Sélection', b: 'Boon', abv: '6.3%', sz: '8 oz', p: '$11.00', note: 'Foeder-select gueuze on draft', s: 'd', ut: 4.0 }] },
  { slot: 'Bartender Pkg - Lambic', cat: 'Belgian Lambic', drunk: false, m: [{ n: 'Girardin Gueuze 1882 Black Label', b: 'Girardin', abv: '5.0%', sz: '375 ml', p: '$20', note: 'Rare blended lambic (bottle)', s: 'b', ut: 4.3 }, { n: 'De Cam Oude Geuze', b: 'De Cam', abv: '6.2%', sz: '750 ml', p: '$50', note: 'Blend from Boon, Girardin, Lindemans', s: 'b', ut: 4.2 }] },
  { slot: 'Special Event Mixed Ferm', cat: 'Mixed Fermentation', drunk: false, m: [{ n: 'BFM Abbaye de St Bon-Chien 20th Anniversary', b: 'BFM', abv: '11.0%', sz: '750 ml', p: '$40', note: 'Cuvée blend in wine/whiskey/grappa barrels', s: 'b', ut: 4.3 }, { n: 'Kerkom Reuss', b: 'Kerkom', abv: '6.5%', sz: '750 ml', p: '$36', note: 'Bink Blond blended w/ Girardin + Boon lambic', s: 'b', ut: 4.1 }] },
  { slot: 'Bartender Draft - Mixed Ferm', cat: 'Mixed Fermentation', drunk: false, m: [{ n: 'Liefmans Oud Bruin', b: 'Liefmans', abv: '5.0%', sz: '8 oz', p: '$9.50', note: 'Flemish red/brown, mixed-ferm blend', s: 'd', ut: 3.8 }, { n: 'Liquid Riot L.R.V. Blend 3', b: 'Liquid Riot', abv: '6.0%', sz: '12 oz', p: '$9.00', note: 'Oceanside koelschip spontaneous blend', s: 'd', ut: 4.0 }] },
  { slot: 'Bartender Pkg - Mixed Ferm', cat: 'Mixed Fermentation', drunk: false, m: [{ n: 'Russian River Temptation', b: 'Russian River', abv: '7.5%', sz: '375 ml', p: '$25', note: 'Brett Chardonnay (bottle)', s: 'b', ut: 4.1 }, { n: 'Russian River Supplication', b: 'Russian River', abv: '7.5%', sz: '375 ml', p: '$25', note: 'Sour brown ale, Pinot Noir barrels + cherries', s: 'b', ut: 4.3 }, { n: 'Allagash Cellars #13', b: 'Allagash', abv: '6.5%', sz: '375 ml', p: '$25', note: 'Peach + elderflower sour blonde', s: 'b', ut: 4.0 }, { n: 'Oxbow Fifteen Years Cuvée', b: 'Oxbow', abv: '7.5%', sz: '500 ml', p: '$25', note: '15-yr blended BA farmhouse', s: 'b', ut: 4.1 }] },
  { slot: 'Fonta Flora Fruit Choice', cat: 'Fruit Beers', drunk: false, m: [] },
  { slot: 'Oxbow Wine Grape Choice', cat: 'Fruit Beers', drunk: false, m: [{ n: 'Oxbow Blue Noir', b: 'Oxbow', abv: '7.0%', sz: '500 ml', p: '$25', note: 'Blueberry + Pinot Noir (bottle)', s: 'b', ut: 3.9 }] },
  { slot: 'Special Event Fruited', cat: 'Fruit Beers', drunk: false, m: [{ n: 'Allagash Coolship Camerise', b: 'Allagash', abv: '6.7%', sz: '8 oz', p: '$10.50', note: 'Spontaneous ale w/ Quebec honeyberries', s: 'd', ut: 4.1 }, { n: 'LoverBeer BeerBrugna', b: 'LoverBeer', abv: '6.2%', sz: '330 ml', p: '$12', note: 'BA mixed-ferm w/ Damaschin plums', s: 'b', ut: 4.2 }, { n: 'LoverBeer BeerBera', b: 'LoverBeer', abv: '8.0%', sz: '330 ml', p: '$12', note: 'BA mixed-ferm w/ Barbera red wine grapes', s: 'b', ut: 4.2 }] },
  { slot: 'Bartender Draft - Fruit Beer', cat: 'Fruit Beers', drunk: true, m: [{ n: 'Allagash Coolship Camerise', b: 'Allagash', abv: '6.7%', sz: '8 oz', p: '$10.50', note: 'Spontaneous ale w/ Quebec honeyberries', s: 'd', ut: 4.1 }] },
  { slot: 'Bartender Pkg - Fruit Beer', cat: 'Fruit Beers', drunk: false, m: [] },
  { slot: 'English Cider Choice', cat: 'Cider', drunk: true, m: [{ n: 'Samuel Smith Organic Cider', b: 'Sam Smith', abv: '5.0%', sz: '12 oz', p: '$10.00', note: 'Off-dry English organic cider', s: 'd', ut: 3.7 }] },
  { slot: 'Spanish Cider Choice', cat: 'Cider', drunk: false, m: [] },
  { slot: 'French Cider Choice', cat: 'Cider', drunk: false, m: [] },
  { slot: 'American Cider', cat: 'Cider', drunk: true, m: [{ n: 'Absolem Cider Woodlander', b: 'Absolem', abv: '6.5%', sz: '10 oz', p: '$10.00', note: 'Single-varietal RI Greening cider on draft', s: 'd', ut: 3.9 }] },
  { slot: 'Choice Cider / Wine Hybrid', cat: 'Cider', drunk: false, m: [] },
  { slot: 'Milko Tube Choice', cat: 'Culturally Important', drunk: true, m: [] },
  { slot: 'Vault Pick Choice', cat: 'Culturally Important', drunk: false, m: [] },
  { slot: 'Mass Choice', cat: 'Culturally Important', drunk: false, m: [] },
  { slot: 'Staff Choice', cat: 'Culturally Important', drunk: false, m: [] },
];
